// Copyright (C) Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: GPL-3.0-or-later

// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

import { test, expect } from "./fixtures.js";
import { waitForAppReady, openMyApps } from "./helpers.js";
import { computeMetadataCid, getApp } from "./registry.js";
import { gatewayFetchJson } from "./bulletin-gateway.js";

// Requires SIGNER to be a funded, h160-mapped account — one balance,
// accessible via either ss58 or h160 (Revive.map_account() links them;
// setup.ts handles mapping). CI runs with E2E_FUNDER_SEED set via repo
// secret; local runs without the secret will fail loudly (no auto-
// fallback to //Alice for write tests). See e2e/README.md "Signing
// identity".
test.describe("publish flow", () => {
  test("publish modal opens from My Apps and shows all required fields", async ({ testHost }) => {
    const frame = await waitForAppReady(testHost);
    await openMyApps(frame);

    await frame.locator('[data-testid="publish-app-btn"]').click();
    const modal = frame.locator('[data-testid="publish-modal"]');
    await expect(modal).toBeVisible();

    await expect(modal.locator('[data-testid="field-domain"]')).toBeVisible();
    await expect(modal.locator('[data-testid="field-name"]')).toBeVisible();
    await expect(modal.locator('[data-testid="field-description"]')).toBeVisible();
    await expect(modal.locator('[data-testid="field-repo-url"]')).toBeVisible();
    await expect(modal.locator('[data-testid="field-tag"]')).toBeVisible();
    await expect(modal.locator('[data-testid="publish-submit-btn"]')).toBeVisible();
    await expect(modal.locator('[data-testid="publish-cancel-btn"]')).toBeVisible();
  });

  test("cancel closes the modal without publishing", async ({ testHost }) => {
    const frame = await waitForAppReady(testHost);
    await openMyApps(frame);

    await frame.locator('[data-testid="publish-app-btn"]').click();
    const modal = frame.locator('[data-testid="publish-modal"]');
    await expect(modal).toBeVisible();

    await modal.locator('[data-testid="publish-cancel-btn"]').click();
    await expect(modal).not.toBeVisible();
  });

  test("submit button is disabled until required fields are filled", async ({ testHost }) => {
    const frame = await waitForAppReady(testHost);
    await openMyApps(frame);

    await frame.locator('[data-testid="publish-app-btn"]').click();
    const modal = frame.locator('[data-testid="publish-modal"]');
    const submit = modal.locator('[data-testid="publish-submit-btn"]');

    await expect(submit).toBeDisabled();

    // Domain alone — still disabled (name required).
    await modal.locator('[data-testid="field-domain"]').fill("e2e-validation");
    await expect(submit).toBeDisabled();

    // Domain + name — enabled.
    await modal.locator('[data-testid="field-name"]').fill("E2E Validation App");
    await expect(submit).toBeEnabled();
  });

  // FIXME(product-sdk descriptors): iframe tx submission hangs because
  // chain-client's bundled @parity/product-sdk-descriptors is out of sync
  // with the current Paseo Asset Hub runtime — submit promise never settles.
  // Reactivate once descriptors are regenerated and chain-client is bumped.
  test.fixme("publishes a unique domain end-to-end and the metadata round-trips", async ({ testHost, throwaway }) => {
    const frame = await waitForAppReady(testHost);
    await openMyApps(frame);

    // Form values we'll later assert flowed through Bulletin → registry → gateway.
    const formValues = {
      name: "E2E Throwaway",
      description: "Generated by publish.spec.ts",
      repository: "https://github.com/paritytech/playground-app",
    };

    await frame.locator('[data-testid="publish-app-btn"]').click();
    const modal = frame.locator('[data-testid="publish-modal"]');
    await expect(modal).toBeVisible();

    await modal.locator('[data-testid="field-domain"]').fill(throwaway.slug);
    await modal.locator('[data-testid="field-name"]').fill(formValues.name);
    await modal.locator('[data-testid="field-description"]').fill(formValues.description);
    await modal.locator('[data-testid="field-repo-url"]').fill(formValues.repository);

    await modal.locator('[data-testid="publish-submit-btn"]').click();

    // Wait for the success state (Bulletin upload + registry tx complete).
    await expect(modal.locator('[data-testid="publish-success"]')).toBeVisible({ timeout: 120_000 });

    // Registry confirms the row exists. The publish-success UI proves the
    // tx was submitted; this proves it was actually included.
    const entry = await getApp(throwaway.domain);
    expect(entry, `registry must contain '${throwaway.domain}' after publish-success`).not.toBeNull();

    // The CID stored on-chain must equal the CID computed from the exact
    // values the user typed. A loose `bafk*` regex would pass even if the
    // upload silently grabbed leftover content from another flow.
    //
    // The app builds the metadata object from the same fields we filled, so
    // we reconstruct it here in the same shape. If the app's serialization
    // shape changes, this assertion fails noisily — which is the point.
    const expectedCid = await computeMetadataCid(formValues);
    expect(entry!.metadataUri, "on-chain CID must equal CID computed from form values")
      .toBe(expectedCid);

    // Round-trip from the Bulletin gateway: the JSON the user entered must
    // be the JSON anyone else fetches. Catches bugs where the upload payload
    // diverges from the form (lossy serialization, wrong encoding, etc.)
    // that an on-chain-only check cannot.
    const fetched = await gatewayFetchJson(entry!.metadataUri);
    expect(fetched).toMatchObject(formValues);
  });
});
