// Copyright (C) Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: GPL-3.0-or-later

// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

/**
 * Verified-identity helpers: build the identity-binding message, run the
 * reveal transaction against the registry, and read the People-chain DotNS
 * username bound to an account's root.
 *
 * Identity model (this replaces the old in-app username claim): a user binds
 * their playground H160 to a DotNS *root* AccountId32 by signing a message
 * with that root account, which the registry verifies (sr25519) and stores via
 * `set_identity` (which also provisions network resources — becoming a builder
 * is one bundled call). The displayed name then resolves through the People
 * chain (`resolveUsernames`) rather than a contract-stored handle. Becoming a
 * builder is permanent — there is no un-reveal. The old `username.ts` hooks
 * stay live until the contract is redeployed (see Task 13).
 */

import * as Sentry from "@sentry/react";
import { useEffect, useState, useSyncExternalStore } from "react";
import { hexToBytes, utf8ToBytes } from "@parity/product-sdk-utils";
import { ss58Encode } from "@parity/product-sdk-address";
import {
  contractsReady,
  individualityReady,
  peopleChainDescriptor,
  signerManager,
  attemptMnemonicTopUp,
} from "./contracts.ts";
import { faucetFailedFromEvents } from "./event-stream/txEvents.ts";
import { withDeadline, withReadDeadline, SUBMIT_DEADLINE_MS } from "./deadline.ts";
import type { PlaygroundRegistryContract } from "./contracts.ts";
import { runTx } from "./diagnostics.ts";
import { isSigningRejection } from "../lib/telemetry";
import { stringify } from "./stringify.ts";
import { resolveUsernames, ZERO_ROOT } from "./peopleIdentity.ts";
import { signIdentityMessage } from "./dotnsSigning.ts";

/** Domain separator for the identity-binding message. Must match the contract. */
const IDENTITY_DOMAIN = "playground.dot identity v1\n";

/**
 * Outcome of a reveal/clear transaction. Mirrors `ClaimUsernameOutcome` in
 * `username.ts` so callers can share toast-copy branching.
 */
// "ok-unfunded" = identity bound successfully, but the bundled faucet was dry
// (contract emitted `FaucetFailed`), so the new builder holds no spendable
// tokens. Callers treat it like "ok" for the gate but tell the user the funding
// failed on our side.
export type IdentityTxOutcome = "ok" | "ok-unfunded" | "rejected" | "failed";

// ---------------------------------------------------------------------------
// Registry identity methods (set_identity / get_root_account[s]).
//
// The current cdm.json ABI may still describe the OLD username surface (it's
// regenerated by `cdm install` only after the contract is redeployed — Task
// 13). So the typed contract handle doesn't yet expose these methods. We
// declare a minimal, type-safe interface for just them and cast the handle to
// it at the call sites. The shapes mirror the cdm `Contract` query/tx surface:
// reads → `{ success, value }`, writes → `{ ok }` (the only field runTx reads).
//
// TODO: drop cast after cdm install regenerates types (Task 13).
// ---------------------------------------------------------------------------
type QueryResult<T> = { success: boolean; value?: T };
type TxResult = { ok?: boolean; events?: readonly unknown[] };
type TxOpts = Parameters<Parameters<typeof runTx>[1]>[0];

interface RegistryWithIdentity {
  setIdentity: {
    tx: (rootPubkey: `0x${string}`, signature: number[], opts: TxOpts) => Promise<TxResult>;
  };
  getRootAccount: {
    query: (address: `0x${string}`) => Promise<QueryResult<`0x${string}`>>;
  };
  getRootAccounts: {
    query: (addresses: `0x${string}`[]) => Promise<QueryResult<`0x${string}`[]>>;
  };
}

function asIdentityRegistry(registry: PlaygroundRegistryContract): RegistryWithIdentity {
  // TODO: drop cast after cdm install regenerates types (Task 13).
  return registry as unknown as RegistryWithIdentity;
}

// ---------------------------------------------------------------------------
// Message builder
// ---------------------------------------------------------------------------

/**
 * Build the INNER identity-binding message the user signs with their DotNS
 * root account:
 *
 *   utf8("playground.dot identity v1\n") || contractAddr(20) || callerH160(20)
 *
 * NO `<Bytes>…</Bytes>` wrap here — the frontend passes the inner bytes. Whether
 * the host wraps them before signing is platform-dependent (Android wraps, iOS
 * signs the inner bytes raw), so the contract's `set_identity` verifies the
 * signature against BOTH the wrapped and raw forms (see `verify_identity_signature`).
 */
export function buildIdentityMessage(
  contractAddr: `0x${string}`,
  callerH160: `0x${string}`,
): Uint8Array {
  const domain = utf8ToBytes(IDENTITY_DOMAIN);
  const contract = hexToBytes(strip0x(contractAddr));
  const caller = hexToBytes(strip0x(callerH160));
  const out = new Uint8Array(domain.length + contract.length + caller.length);
  out.set(domain, 0);
  out.set(contract, domain.length);
  out.set(caller, domain.length + contract.length);
  return out;
}

/** `hexToBytes` (noble) rejects a `0x` prefix; strip it first, like the repo's
 *  other hex→bytes call sites. */
function strip0x(hex: string): string {
  return hex.startsWith("0x") ? hex.slice(2) : hex;
}

// ---------------------------------------------------------------------------
// Revealed snapshot
//
// "Revealed" (identity bound) is the onboarding gate, and the gate has to be
// readable synchronously and OUTSIDE React — `guardedWrite` (a plain function
// above the provider in the tree) decides whether a write should route to the
// Become-a-builder flow vs. a faucet top-up before any tx fires. So we mirror
// the resources snapshot in `utils/resources.ts`: a per-H160 localStorage memo
// that only ever records the positive. Identity binding is permanent on-chain
// (revealed never regresses to anonymous in the new model), so a cached `true`
// is authoritative and a failed/absent read never downgrades it.
// ---------------------------------------------------------------------------

const REVEALED_SNAPSHOT_KEY = "pg.identity.v1";

/** True iff `h160` has previously been recorded as revealed (identity bound). */
export function readRevealedSnapshot(h160: string): boolean {
  try {
    const raw = localStorage.getItem(REVEALED_SNAPSHOT_KEY);
    if (!raw) return false;
    const map = JSON.parse(raw) as Record<string, boolean>;
    return map[h160.toLowerCase()] === true;
  } catch {
    return false;
  }
}

/**
 * Record that `h160` is revealed, optimistically. Called the instant a reveal
 * tx lands "ok" and whenever a bound root is read back, so the gate flips
 * without waiting on People-chain name resolution or a chain re-read.
 */
export function confirmRevealed(h160: string): void {
  try {
    const raw = localStorage.getItem(REVEALED_SNAPSHOT_KEY);
    const map = raw ? (JSON.parse(raw) as Record<string, boolean>) : {};
    map[h160.toLowerCase()] = true;
    localStorage.setItem(REVEALED_SNAPSHOT_KEY, JSON.stringify(map));
  } catch {
    /* storage full / unavailable — snapshot is an optimisation only */
  }
}

/**
 * Authoritative "is this account a builder yet?" for non-React callers
 * (`guardedWrite`). The cached positive short-circuits the chain read; a
 * never-revealed account falls back to {@link hasRevealedIdentity}. A `null`
 * read (failure) is treated as not-revealed for gating — conservative, and the
 * snapshot covers the common already-revealed case so the read rarely runs.
 */
export async function isRevealedNow(h160: string): Promise<boolean> {
  if (readRevealedSnapshot(h160)) return true;
  return (await hasRevealedIdentity(h160)) === true;
}

// ---------------------------------------------------------------------------
// Reveal / clear transactions
//
// Same gas/storage pinning + waitFor pattern + Sentry instrumentation as the
// old `claimUsername`: set_identity inserts new storage slots, so the SDK
// estimator can undershoot → pin the limits high to bypass it.
// ---------------------------------------------------------------------------

const IDENTITY_TX_OPTS = {
  waitFor: "best-block" as const,
  gasLimit: { ref_time: 1_500_000_000_000n, proof_size: 2_000_000n },
  storageDepositLimit: 1_000_000_000_000n,
};

/**
 * Reveal the connected user's verified identity: have them sign the
 * identity-binding message with their DotNS root account, then submit
 * `set_identity(root_pubkey, signature)` to the registry. Never throws — maps
 * a signing rejection → "rejected", any other error → "failed", success → "ok".
 */
export async function revealIdentity(callerH160: `0x${string}`): Promise<IdentityTxOutcome> {
  try {
    const { registry, registryAddress } = await contractsReady;
    const message = buildIdentityMessage(registryAddress as `0x${string}`, callerH160);

    // The signing rejection can surface here (the user declines the host's
    // sign prompt) — handled by the shared isSigningRejection branch below.
    // Pass the People-chain DESCRIPTOR (PR #212 manages its own connection) and
    // OMIT username so the SDK falls back to the host's primary DotNS name.
    const { accountId, signature } = await signIdentityMessage({
      peopleChain: peopleChainDescriptor,
      message,
    });

    // Bound the submit (#409): same wedge-on-Android hang as the no-arg path —
    // the set_identity ack never resolves and "reserving your handle" hangs
    // forever. DeadlineError is caught below → "failed". set_identity is
    // idempotent, so re-running after a deadline is safe (matches the observed
    // "restart + retry worked" workaround). The signing prelude above is
    // separately capped by the host (60s SIGNING_TIMEOUT_MS), so only the
    // non-interactive submit needs this wrap.
    const res = await withDeadline(
      runTx(
        "setIdentity",
        (opts) =>
          asIdentityRegistry(registry).setIdentity.tx(accountId, Array.from(signature), opts),
        { action: "reveal-identity" },
        IDENTITY_TX_OPTS,
      ),
      SUBMIT_DEADLINE_MS,
      "setIdentity",
    );
    if ((res as TxResult).ok === false) {
      console.warn(`[playground] setIdentity returned ok=false: ${stringify(res)}`);
      // ok=false never throws, so nothing else records it — capture so the
      // failure is grouped + queryable (mirrors claimUsername).
      Sentry.captureMessage("[tx setIdentity] result.ok=false", {
        level: "error",
        extra: { result: stringify(res) },
        tags: { action: "reveal-identity", "tx.error": "result.ok=false" },
      });
      return "failed";
    }
    // Identity bound — record the positive so the gate flips immediately,
    // before People-chain name resolution or a post-tx chain re-read.
    confirmRevealed(callerH160);
    // The bundled `set_identity` faucet (F) is best-effort and emits
    // `FaucetFailed` (without reverting) when the contract is dry. If it did,
    // fall back to the no-phone-signature mnemonic funders (dedicated → Alice)
    // so the first-time funding order is F → D → A. The reveal's single phone
    // signature already happened above, so D/A run silently.
    if (faucetFailedFromEvents((res as TxResult).events ?? [], registryAddress)) {
      console.warn(`[playground] faucet is dry on reveal — FaucetFailed for ${callerH160}`);
      const recipientSs58 = signerManager.getState().selectedAccount?.address;
      const funded = recipientSs58 ? await attemptMnemonicTopUp(recipientSs58) : false;
      if (funded) return "ok";
      // Every funder failed: the user is a builder but holds no spendable
      // tokens — flag it so the caller says it's on our side.
      Sentry.captureMessage("faucet empty on reveal", {
        level: "warning",
        tags: { action: "faucet-empty" },
      });
      return "ok-unfunded";
    }
    return "ok";
  } catch (cause) {
    if (isSigningRejection(cause)) return "rejected";
    console.warn(`[playground] revealIdentity threw: ${stringify(cause)}`);
    Sentry.captureException(cause, {
      tags: {
        action: "reveal-identity",
        ...(cause instanceof Error ? { "tx.error": cause.message.slice(0, 200) } : {}),
      },
    });
    return "failed";
  }
}

// ---------------------------------------------------------------------------
// People-chain resolution
//
// The live `client.individuality.query.Resources.Consumers` keys by
// SS58String, but our root accounts are 0x-hex AccountId32 (the contract
// returns bytes32). So we wrap the live client in a structural adapter whose
// `getValues` SS58-encodes each hex root before querying; `resolveUsernames`
// re-keys the (index-aligned) results back to hex itself.
// ---------------------------------------------------------------------------

type ConsumerInfo = { full_username?: Uint8Array | null; lite_username?: Uint8Array | null };

type IndividualityHandle = {
  query: {
    Resources: { Consumers: { getValues: (keys: [string][]) => Promise<(ConsumerInfo | undefined)[]> } };
  };
};

/**
 * Wrap the live individuality handle so `resolveUsernames` can pass 0x-hex
 * roots: each key is SS58-encoded (default/generic prefix — the People-chain
 * storage key hashes the decoded 32 bytes, so the prefix is immaterial) before
 * hitting the live `Resources.Consumers` storage, which keys by SS58String.
 * Results stay
 * index-aligned, so `resolveUsernames` maps them back onto the original hex.
 */
function ss58ResolverAdapter(client: IndividualityHandle): IndividualityHandle {
  return {
    query: {
      Resources: {
        Consumers: {
          getValues: (keys) =>
            client.query.Resources.Consumers.getValues(
              keys.map(([hex]) => [ss58Encode(hexToBytes(strip0x(hex)))] as [string]),
            ),
        },
      },
    },
  };
}

/** Read a single account's root binding, or `null` if anonymous/unset. */
async function readRoot(account: `0x${string}`): Promise<`0x${string}` | null> {
  const { registry } = await contractsReady;
  const res = await withReadDeadline(
    asIdentityRegistry(registry).getRootAccount.query(account),
    "Registry root account",
  );
  if (!res.success) {
    console.warn(
      `[playground] registry.getRootAccount(${account}) returned success:false — ${stringify(res)}`,
    );
    return null;
  }
  const root = (res.value ?? ZERO_ROOT) as `0x${string}`;
  return root === ZERO_ROOT ? null : root;
}

/**
 * Whether an account has bound (revealed) a verified identity — i.e. its root
 * account is non-zero. `null` on read failure (distinguishable from a confirmed
 * `false`), so callers using the never-regress rule can skip the write. This is
 * the identity-era replacement for the old "has a username" milestone check.
 */
export async function hasRevealedIdentity(addr: string): Promise<boolean | null> {
  try {
    const { registry } = await contractsReady;
    const res = await withReadDeadline(
      asIdentityRegistry(registry).getRootAccount.query(addr as `0x${string}`),
      "Registry root account",
    );
    if (!res.success) return null;
    return ((res.value ?? ZERO_ROOT) as `0x${string}`) !== ZERO_ROOT;
  } catch {
    return null;
  }
}

/**
 * Async (non-hook) batch resolve: accounts -> People-chain usernames in one
 * contract read + one host storage batch. Used by event-stream sources and as
 * the engine behind {@link useRootUsernamesBatch}. Returns a Map keyed by
 * lowercased H160 (anonymous / unresolved -> null). Empty input -> empty Map.
 */
export async function resolveRootUsernames(
  accounts: readonly `0x${string}`[],
): Promise<Map<string, string | null>> {
  if (accounts.length === 0) return new Map();

  // Dedupe on the lowercased form — callers may pass the same owner twice.
  const unique = [...new Set(accounts.map((a) => a.toLowerCase() as `0x${string}`))];

  const { registry } = await contractsReady;
  const res = await withReadDeadline(
    asIdentityRegistry(registry).getRootAccounts.query(unique as `0x${string}`[]),
    "Registry root accounts",
  );
  if (!res.success) {
    console.warn(
      `[playground] registry.getRootAccounts(${unique.length}) returned success:false — ${stringify(res)}`,
    );
    return new Map();
  }
  const roots = (res.value ?? []) as `0x${string}`[];

  // ONE batched People-chain round-trip for the non-zero roots; zero roots
  // resolve to null inside resolveUsernames.
  const client = await individualityReady;
  const names = await resolveUsernames(
    ss58ResolverAdapter(client as IndividualityHandle),
    roots,
  );

  const out = new Map<string, string | null>();
  for (let i = 0; i < unique.length; i++) {
    const root = roots[i] ?? ZERO_ROOT;
    out.set(unique[i], root === ZERO_ROOT ? null : (names.get(root) ?? null));
  }
  return out;
}

// Anti-flash cache: last CONFIRMED username per lowercased H160 (mirrors
// `username.ts`'s `usernameCache`). Survives unmounts so a remount doesn't
// flash the anonymous fallback while the read re-runs. `undefined` = unknown.
const rootUsernameCache = new Map<string, string | null>();

// ---------------------------------------------------------------------------
// Broadcast store (mirrors `username.ts`'s `revalidateRegistryUsernames`).
//
// `useRootUsername` is otherwise refreshed only via its `refreshKey` prop,
// bumped after a LOCAL reveal/clear tx. But a reveal/clear can also land from
// elsewhere (the CLI, a second tab) — surfaced here as an IdentityLinked /
// IdentityCleared / IdentityBonusAwarded event. The identity payload carries
// the recipient but the per-account reads aren't event-driven, so the cheapest
// correct reaction is a broadcast re-read in every mounted hook.
// ---------------------------------------------------------------------------
let identityStoreVersion = 0;
const identityStoreListeners = new Set<() => void>();

function subscribeIdentityStore(listener: () => void): () => void {
  identityStoreListeners.add(listener);
  return () => identityStoreListeners.delete(listener);
}

function getIdentityStoreVersion(): number {
  return identityStoreVersion;
}

/**
 * Force every mounted `useRootUsername` to re-read from chain. Called from the
 * registry event dispatcher on identity events (reveal/clear done elsewhere).
 */
export function revalidateRootIdentities(): void {
  identityStoreVersion++;
  for (const l of identityStoreListeners) l();
}

/** Retry pacing after a failed read (mirrors `username.ts`). */
const READ_RETRY_DELAYS_MS = [2_000, 5_000, 10_000];

/**
 * Watch a single account's verified DotNS username (via its root binding).
 * `null` = chain confirmed no binding / no name (anonymous); `undefined` =
 * not known yet (never flash a fallback over this). Uses a retry + anti-flash
 * cache so a flaky read never downgrades a known name.
 */
export function useRootUsername(
  account: `0x${string}` | undefined | null,
  refreshKey: number = 0,
): {
  username: string | null | undefined;
  loading: boolean;
  refresh: () => void;
} {
  const [username, setUsername] = useState<string | null | undefined>(() =>
    account ? rootUsernameCache.get(account.toLowerCase()) : null,
  );
  const [loading, setLoading] = useState(false);
  const [localKey, setLocalKey] = useState(0);
  // A bump here (via `revalidateRootIdentities`) re-fires the read effect so a
  // reveal/clear done elsewhere (CLI, second tab) updates this hook too.
  const storeVersion = useSyncExternalStore(subscribeIdentityStore, getIdentityStoreVersion);

  useEffect(() => {
    if (!account) {
      setUsername(null);
      return;
    }
    const key = account.toLowerCase();
    // Paint the cached value immediately so a remount never flashes the
    // anonymous fallback while the read runs.
    setUsername(rootUsernameCache.get(key));

    let cancelled = false;
    let retryTimer: ReturnType<typeof setTimeout> | undefined;
    let attempt = 0;

    const scheduleRetry = () => {
      if (attempt >= READ_RETRY_DELAYS_MS.length) return;
      retryTimer = setTimeout(() => {
        if (!cancelled) void read();
      }, READ_RETRY_DELAYS_MS[attempt++]);
    };

    const read = async () => {
      setLoading(true);
      try {
        const root = await readRoot(account);
        if (cancelled) return;
        if (root === null) {
          rootUsernameCache.set(key, null);
          setUsername(null);
          return;
        }
        // A bound root means this account is a builder — record it so the gate
        // is correct even before (or without) a resolved People-chain name.
        confirmRevealed(key);
        const client = await individualityReady;
        const names = await resolveUsernames(
          ss58ResolverAdapter(client as IndividualityHandle),
          [root],
        );
        if (cancelled) return;
        const name = names.get(root) ?? null;
        rootUsernameCache.set(key, name);
        setUsername(name);
      } catch (cause) {
        if (cancelled) return;
        // A failed read NEVER downgrades a known name — keep the cached value
        // (painted above) and retry with backoff (mirrors #324).
        console.warn(
          `[playground] useRootUsername(${account}) read failed — ${stringify(cause)}`,
        );
        scheduleRetry();
      } finally {
        if (!cancelled) setLoading(false);
      }
    };

    void read();
    return () => {
      cancelled = true;
      if (retryTimer !== undefined) clearTimeout(retryTimer);
    };
  }, [account, refreshKey, localKey, storeVersion]);

  return {
    username,
    loading,
    refresh: () => setLocalKey((k) => k + 1),
  };
}

/**
 * Batch-read verified DotNS usernames for a list of addresses (leaderboard).
 * One `get_root_accounts` call + ONE batched `resolveUsernames` per
 * address-set change. Returns a Map keyed by lowercased H160 (anonymous →
 * null). Wraps the async {@link resolveRootUsernames} with a stable-key deps
 * pattern so an inline-built address list doesn't re-fire on every render.
 */
export function useRootUsernamesBatch(
  addresses: ReadonlyArray<`0x${string}`>,
  refreshKey: number = 0,
): Map<string, string | null> {
  const [map, setMap] = useState<Map<string, string | null>>(new Map());

  // Stable key for the deps array — comparing the array by reference would
  // re-fire on every render when callers build the list inline.
  const key = addresses.map((a) => a.toLowerCase()).join(",");

  useEffect(() => {
    if (addresses.length === 0) {
      setMap(new Map());
      return;
    }
    let cancelled = false;
    (async () => {
      try {
        // The async helper dedupes + re-keys to lowercased H160; the returned
        // Map already covers every unique address the hook was given.
        const next = await resolveRootUsernames(addresses);
        if (cancelled) return;
        setMap(next);
      } catch (cause) {
        if (cancelled) return;
        console.warn(
          `[playground] useRootUsernamesBatch(${addresses.length}) failed — ${stringify(cause)}`,
        );
      }
    })();
    return () => {
      cancelled = true;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps -- key is the
    // canonical form of `addresses` (see comment above).
  }, [key, refreshKey]);

  return map;
}
